
"use client";
import Link from "next/link";
import  {usePathname}  from "next/navigation";
import "./styles.css";

// export const metadata = {
//   title: {
//     default: "Welcome to Gallery", 
//     template: "%s | Gallery"
//   },
//   description: "Generated by Next.js",
// };

const navigation_map = [
  {title: "Home", href:"/"},
  {title: "Blog", href:"/blog"},
  {title: "Product", href:"/product"},

]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <div style={{ backgroundColor: "aqua" }}>
          { 
               
            navigation_map.map((link) => {
              const isActive = pathname.startsWith(link.href);
              return (<Link className={isActive? "font-bold m-4": "text-blue-800 m-4"} href={link.href}> {link.title} </Link>)
            })
          }
        </div>
        {children}
        <footer style={{ backgroundColor: "aqua" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
