export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div style={{ backgroundColor: "aqua" }}>
          <p>Header</p>
        </div>
        {children}
        <footer style={{ backgroundColor: "aqua" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
